<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="studyplan" nsURI="platform:/plugin/tdt4250.studyplan.model/model/studyplan.ecore"
    nsPrefix="studyplan">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/acceleo/query/1.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="totalNrOfSemestersShouldMatchType masterLevelHasMaxLimitOfLevelThreeCoures allMainSpecsSimilarDuration mandatoryCoursesCovered noDuplicateCourses"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="totalNrOfSemestersShouldMatchType" value="self.specializations.subSpecializations->forAll(sub | sub.semesters->union(sub.eContainer().semesters)->union(sub.eContainer().eContainer().semesters)->size() = self.type.value)"/>
      <details key="allMainSpecsSimilarDuration" value="self.specializations->forAll(spe | spe.semesters.programsSemesterOrderNr->union(spe.subSpecializations.semesters.programsSemesterOrderNr)->asSet()->size() = self.specializations->first().semesters.programsSemesterOrderNr->union(self.specializations.subSpecializations.semesters.programsSemesterOrderNr)->asSet()->size())"/>
      <details key="mandatoryCoursesCovered" value="self.specializations.subSpecializations->forAll(sub | sub.semesters.mandatoryCourses->union(sub.eContainer().semesters.mandatoryCourses)->union(sub.eContainer().eContainer().semesters.mandatoryCourses)->includesAll(self.mandatoryCourses))"/>
      <details key="noDuplicateCourses" value="self.specializations.subSpecializations->forAll(sub | sub.semesters.mandatoryCourses->union(sub.eContainer().semesters.mandatoryCourses)->union(sub.eContainer().eContainer().semesters.mandatoryCourses)->isUnique(c | c.code))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ProgramTypeAndDuration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specializations" upperBound="-1"
        eType="#//Specialization" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" upperBound="-1"
        eType="#//Semester" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatoryCourses" upperBound="-1"
        eType="#//Course"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="hasValidCreditValue codeIsUnique taughtInAutumnOrSpring"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="codeIsUnique" value="self.eContainer().courses->isUnique(course | course.code)"/>
      <details key="taughtInAutumnOrSpring" value=" self.taughtInAutumn or self.taughtInSpring"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="#//CourseCode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//CourseLevel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taughtInAutumn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taughtInSpring" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CourseCode" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ProgramTypeAndDuration">
    <eLiterals name="Bachelor" value="6"/>
    <eLiterals name="Master" value="4"/>
    <eLiterals name="IntegratedMaster" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CourseLevel">
    <eLiterals name="level1"/>
    <eLiterals name="level2" value="1"/>
    <eLiterals name="level3" value="2"/>
    <eLiterals name="higher" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialization">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="allSubspecsSimilarLength mandatoryCoursesAreCovered"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="mandatoryCoursesAreCovered" value="self.subSpecializations->forAll(sub | sub.semesters.mandatoryCourses->union(sub.eContainer().semesters.mandatoryCourses)->includesAll(self.mandatoryCourses))"/>
      <details key="allSubspecsSimilarLength" value="self.subSpecializations->forAll(sub | sub.semesters->size() = self.subSpecializations->first().semesters->size())"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subSpecializations" upperBound="-1"
        eType="#//Specialization" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatoryCourses" upperBound="-1"
        eType="#//Course"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" lowerBound="1"
        upperBound="-1" eType="#//Semester" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="shouldContainEnoughCredits coursesTaughtCurrentSemester optionGroupsCorrectSemester"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="shouldContainEnoughCredits" value="self.totalCreditsValue >= 30.0"/>
      <details key="optionGroupsCorrectSemester" value="self.optionalCourseGroups->forAll(optionalGroup | optionalGroup.semester = self)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="programsSemesterOrderNr"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optionalCourseGroups" upperBound="-1"
        eType="#//SemesterOptionalCourseGroup" containment="true" eOpposite="#//SemesterOptionalCourseGroup/semester"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalCreditsValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatoryCourses" upperBound="-1"
        eType="#//Course"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemesterOptionalCourseGroup">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nrOfOptionalMustBeLessThanSizeOfGroup currentlySelectedInOptions currentlySelectedCorrectSize"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="nrOfOptionalMustBeLessThanSizeOfGroup" value="self.optionalCourses->size() >= self.nrOfOptionalFromGroup"/>
      <details key="currentlySelectedCorrectSize" value="self.currentlySelected->size() &lt;= self.nrOfOptionalFromGroup"/>
      <details key="currentlySelectedInOptions" value="self.optionalCourses->includesAll(self.currentlySelected)"/>
    </eAnnotations>
    <eOperations name="selectOptionalCourse">
      <eParameters name="course" eType="#//Course"/>
    </eOperations>
    <eOperations name="unselectOptionalCourse">
      <eParameters name="course" eType="#//Course"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nrOfOptionalFromGroup"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semester" lowerBound="1"
        eType="#//Semester" eOpposite="#//Semester/optionalCourseGroups"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentlySelected" upperBound="-1"
        eType="#//Course" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optionalCourses" upperBound="-1"
        eType="#//Course"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Studyplan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programs" upperBound="-1"
        eType="#//Program" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
