<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="studyplan" nsURI="platform:/plugin/tdt4250.studyplan.model/model/studyplan.ecore"
    nsPrefix="studyplan">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/acceleo/query/1.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="totalNrOfSemestersShouldMatchType masterLevelHasMaxLimitOfLevelThreeCoures allSpecsDurationShorterThanProgram allMainSpecsSimilarDuration mandatoryCoursesCovered semestersHasUniqueOrderNr noDuplicateCourses"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="totalNrOfSemestersShouldMatchType" value="self.type.value = self.semesters->size()"/>
      <details key="allSpecsDurationShorterThanProgram" value="self.specializations->collect(spec | spec.durationInSemesters)->forAll(num | num &lt;= self.type.value)"/>
      <details key="allMainSpecsSimilarDuration" value="self.specializations->select(spec | spec.parentSpecialization = null)->collect(spec | spec.durationInSemesters)->forAll(num | num = self.specializations->first().durationInSemesters)"/>
      <details key="semestersHasUniqueOrderNr" value="self.semesters->isUnique(sem | sem.ProgramsSemesterOrderNr)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ProgramTypeAndDuration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specializations" upperBound="-1"
        eType="#//Specialization" containment="true" eOpposite="#//Specialization/program"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatoryCourses" lowerBound="1"
        eType="#//CourseGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" lowerBound="4"
        upperBound="10" eType="#//Semester" containment="true" eOpposite="#//Semester/program"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durationPreSpecialization"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="hasValidCreditValue codeIsUnique taughtInAutumnOrSpring"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="codeIsUnique" value="self.eContainer().courses->isUnique(course | course.code)"/>
      <details key="taughtInAutumnOrSpring" value=" self.taughtInAutumn or self.taughtInSpring"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="#//CourseCode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//CourseLevel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taughtInAutumn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taughtInSpring" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CourseCode" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ProgramTypeAndDuration">
    <eLiterals name="Bachelor" value="6"/>
    <eLiterals name="Master" value="4"/>
    <eLiterals name="IntegratedMaster" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CourseLevel">
    <eLiterals name="level1"/>
    <eLiterals name="level2" value="1"/>
    <eLiterals name="level3" value="2"/>
    <eLiterals name="higher" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialization">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="allSubspecsSimilarLength subspecsShorterThanParent mandatoryCoursesAreCovered"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="subspecsShorterThanParent" value="self.subSpecializations->collect(spec | spec.durationInSemesters)->forAll(num | num &lt;= self.durationInSemesters)"/>
      <details key="allMainSpecsSimilarDuration" value="self.subSpecializations->collect(subSpec | subSpec.durationInSemesters)->forAll(num | num = self.subSpecializations->first().durationInSemesters)"/>
      <details key="allSubspecsSimilarLength" value="self.subSpecializations->forAll(subSpec | subSpec.size() = self.subSpecialization->first().durationInSemesters)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="program" lowerBound="1"
        eType="#//Program" eOpposite="#//Program/specializations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatoryCourses" lowerBound="1"
        eType="#//CourseGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durationInSemesters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentSpecialization" eType="#//Specialization"
        eOpposite="#//Specialization/subSpecializations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subSpecializations" upperBound="-1"
        eType="#//Specialization" derived="true" eOpposite="#//Specialization/parentSpecialization"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="shouldContainEnoughCredits coursesTaughtCurrentSemester"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="shouldContainEnoughCredits" value="self.totalCreditsValue >= 30.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="programsSemesterOrderNr"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatoryCourses" lowerBound="1"
        eType="#//CourseGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optionalCourseGroups" upperBound="-1"
        eType="#//SemesterOptionalCourseGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="program" lowerBound="1"
        eType="#//Program" eOpposite="#//Program/semesters"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialization" eType="#//Specialization"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalCreditsValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemesterOptionalCourseGroup">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nrOfOptionalMustBeLessThanSizeOfGroup currentlySelectedInOptions currentlySelectedCorrectSize"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="nrOfOptionalMustBeLessThanSizeOfGroup" value="self.courseGroup.courses->size() >= self.nrOfOptionalFromGroup"/>
      <details key="currentlySelectedCorrectSize" value="self.currentlySelected->size() = self.nrOfOptionalFromGroup"/>
      <details key="currentlySelectedInOptions" value="self.courseGroup.courses->includesAll(self.currentlySelected)"/>
    </eAnnotations>
    <eOperations name="selectOptionalCourse">
      <eParameters name="course" eType="#//Course"/>
    </eOperations>
    <eOperations name="unselectOptionalCourse">
      <eParameters name="course" eType="#//Course"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nrOfOptionalFromGroup"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semester" lowerBound="1"
        eType="#//Semester"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseGroup" lowerBound="1"
        eType="#//CourseGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentlySelected" upperBound="-1"
        eType="#//Course" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Studyplan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programs" upperBound="-1"
        eType="#//Program" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
